name: Repository Dispatch

on:
  repository_dispatch:
    types: [new-image]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout
    # - name: Create annotation for build error
    #   run: |
    #     ls
    #     pwd

    # - name: Update Image Version
    #   id: imgupd
    #   uses: mikefarah/yq@master
    #   with:
    #     cmd: yq eval '.deployments[0].spec.template.spec.containers[0].image = "new-image:tag"' -i ./Helm/search-dev/v.yaml
    #     # cmd: yq eval '.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' -i ./Helm/search-dev/values.yaml
    - name: Update Helm Image
      run: |
        yq eval '.deployments[0].spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' -i ./Helm/search-dev/values.yaml
        # yq eval '.services[1].type = "new-image:tag"' -i ./Helm/search-dev/values.yaml



    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply image name changes

